# Generated by Django 2.1.2 on 2018-10-21 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutOpenMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('objectives', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OurProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Our Projects',
            },
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('position', models.CharField(max_length=128)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('instagram', models.URLField()),
                ('linkedin', models.URLField()),
                ('skype', models.URLField()),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team members',
            },
        ),
        migrations.CreateModel(
            name='WhatWeDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenMap.AboutOpenMap')),
            ],
            options={
                'verbose_name_plural': 'What We Do',
            },
        ),
    ]
